---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - wget
      - gnupg
    state: present
    update_cache: true

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Grafana GPG key
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /tmp/grafana.gpg.key
    mode: "0644"

- name: Dearmor Grafana GPG key
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/grafana.gpg /tmp/grafana.gpg.key
    creates: /etc/apt/keyrings/grafana.gpg

- name: Add Grafana APT repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/grafana.list
    content: |
      deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main
    mode: "0644"

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: true

- name: Add notifier to grafana-server service
  ansible.builtin.copy:
    src: override.conf
    dest: /etc/systemd/system/grafana-server.service.d/override.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart grafana-server

- name: Enable and start Grafana
  ansible.builtin.systemd:
    name: grafana-server
    enabled: true
    state: started

