---
- hosts: localhost
  connection: local
  become: yes  # runs everything as root
  roles:
    - initial-setup
    - notifier
    - caddy
    - tailscale
    - seasontracker
    - weather-station-server
    - email-archive
    - docker
    - grafana
    - papra
    - jellyfin
    - immich-scripts
