salary: "TU DELFT/REMI/Salaris"
supermarket: ["JUMBO", "ALBERT HEIJN", "AH To Go", "SPAR ", "MERCADONA", "CONDIS", "CAPRABO", "LIDL", "SUPERMERCADO", "SUPERCOR", "ALDI", "Aldi", "Plus Kleijnen", "AH Nijmegen", "CARREFOUR", "BON AREA", "HEMA", "SUPERVERD", "Bakker Willem", "ETOS"]
hobbies: ["SoSalsa", "REVOLT", "Decathlon", "SALA ESCALADA BAT", "Makerspace", "Delfts Bleau", "TUBOSA", "Snookercafe"]
health_insurance: ["OHRA", "ZORGTOESLAG"]
bike: ["Hans  J  Brand", "Swapfiets", "Zettle_*Hans. J. Brand"]
house: ["Action", "IKEA", "Gamma Delft", "PRAXIS"]
rent: ["DUWO", "HUURTOESLAG"]
restaurants: ["Pavarotti", "Zettle_*Noel", "HMS Host International", "Toko Idola", "Dominos", "McDonald", "VIENA", "Doner King", " DONER "]
flights: ["Vueling", "Transavia", "Ryanair","EASYJET", "KLM"]
public_transport: ["NS Groep", "NS GROEP", "NS Reizigers", "RENFE", "F.G.C.", "METRO BARCELONA", "MONBUS", "FGC MAE", "T MOBILITAT"]
clothes: ["H & M", "MASSIMO DUTTI", "SABATERS"]
SIM: "Lebara"
electronics: ["Media Markt"]
trips: []
hair: ["Blue Hart", "PERRUQUERIES"]
bar: ["snacks", "De Gist", "BAR SIL"]
cinema: []
health: ["FARMACIA", "H&B", "Apotheek"]
presents: []
transfer: ["Deposit at ABN AMRO Savings"]
parties: ["Fiesta Macumba"]
other: []
conference_budget: []
visit_budget: []
games: ["VALVE CORPORATION"]
tolls: ["AUTOPISTAS TERRAS"]
fines: []
turist_attractions: []
erasmus_nuria: []
bank_fee: ["ABN AMRO Bank N.V.               Basic Package", "ABN AMRO Bank N.V.               BasisPakket Betalen"]
visas: ["UKVI"]
