---
- name: Create homepage directory
  ansible.builtin.file:
    path: /var/www/homepage
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy homepage files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /var/www/homepage/
    owner: root
    group: root
    mode: "0644"
  loop:
    - favicon.svg
    - index.html

- name: Copy homepage icons
  ansible.builtin.copy:
    src: icons/
    dest: /var/www/homepage/icons/
    owner: root
    group: root
    mode: "0644"

- name: Create exercicis directory
  ansible.builtin.file:
    path: /var/www/exercicis
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy exercicis files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /var/www/exercicis/
    owner: root
    group: root
    mode: "0644"
  loop:
    - exercicis/index.html

- name: Copy homepage icons
  ansible.builtin.copy:
    src: exercicis/icons/
    dest: /var/www/exercicis/icons/
    owner: root
    group: root
    mode: "0644"

- name: Create random directory
  ansible.builtin.file:
    path: /var/www/random
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy random files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /var/www/random/
    owner: root
    group: root
    mode: "0644"
  loop:
    - random/index.html
